### PR TITLE
Fix #104: php 7.2 handle ini_set() when session already started

### LINKED ISSUE #104: php 7.2 with zend-session 2.8.3 : ini_set(): A session is active  and  'session.use_cookies' is not a valid sessions-related ini setting error
- [x] I was not able to find an [open](https://github.com/zendframework/zend-session/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-session/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

```php
use Zend\Authentication\Storage;

class AuthStorage extends Storage\Session
{
    public function __construct() 
   {
        parent::__construct('auth');

        $sessionConfigOptions = [
            'use_cookies'     => true,
            'cookie_httponly' => true,
            'gc_maxlifetime'  => 8000000 ,
            'cookie_lifetime' => 1800,
        ];
        $this->session->getManager()->getConfig()->setOptions($sessionConfigOptions);
    }
}

$authService = new Zend\Authentication\AuthenticationService(new AuthStorage());
```

### Expected results

Working

### Actual results

Got errors:
-  ini_set(): A session is active. You cannot change the session module's ini settings at this time
- Uncaught Zend\Session\Exception\InvalidArgumentException: 'session.use_cookies' is not a valid sessions-related ini setting

Env:
php version: 7.2
zend-session: 2.8.3

### PR DESCRIPTION
**Pull request by samsonasik**
Provide a narrative description of what you are trying to accomplish:

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
          We can't call `ini_set()` when session already started
  - [x] Detail the original, incorrect behavior.
          When it called, it got error : "ini_set(): A session is active. You cannot change the session module's ini settings at this time"
  - [x] Detail the new, expected behavior.
          It call `session_write_close()` first, then start the session again 
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [x] Add a `CHANGELOG.md` entry for the fix.

### CODE REVIEW

File: src/Config/SessionConfig.php [hunk 1]
```diff
@@ -133,7 +133,18 @@ public function setStorageOption($storageName, $storageValue)
                 break;
         }
 
+        $sessionAlreadyStarted = false;
```
Comment (weierophinney) [inline src/Config/SessionConfig.php]: I'd rename this to `$sessionRequiresRestart`, as it better conveys what needs to happen. This is particularly important when you come to line 144, as calling `session_start()` because `$sessionAlreadyStarted` seems like a mistake when just looking at the verbiage.

File: src/Config/SessionConfig.php [hunk 2]
```diff
@@ -133,7 +133,18 @@ public function setStorageOption($storageName, $storageValue)
...
+        if (session_status() == PHP_SESSION_ACTIVE) {
+            $sessionAlreadyStarted = true;
+            session_write_close();
```
Comment (weierophinney) [inline src/Config/SessionConfig.php]: Honestly, this seems really problematic, considering your original use case as demonstrated in #104. It means that you are _starting_, _stopping_, and _restarting_ your session _on every request_, resulting in I/O _even if no data is ever written or accessed_. This may not seem like a big deal, but it can lead to longer response times (due to I/O of writing the session), and potential concurrency issues.

Wouldn't it be more performant and less prone to error to do as I suggested in that issue and inject the fully configured session manager into your container during instantiation? Have you tried the solution I posted on that issue?

**Review by weierophinney — CHANGES_REQUESTED** [review]

File: src/Config/SessionConfig.php (hunk 2 above)
Comment (samsonasik) [reply src/Config/SessionConfig.php]: Yes, I tried your solution, but that still got issue, for example, on call `sessionmanager ->rememberMe()` after login success that requires changes cookie lifetime, while session already active.

Comment (samsonasik) [reply src/Config/SessionConfig.php]: also when calling `sessionmanager->forgetMe()` as it set cookie_lifetime to 0, while session already started

File: src/Config/SessionConfig.php (hunk 1 above)
Comment (samsonasik) [reply src/Config/SessionConfig.php]: I've updated variable to `sessionRequiresRestart`

**Comment by samsonasik** [comment]
@weierophinney I've updated code to check `session_status()` compare with `PHP_SESSION_ACTIVE` once only before `ini_set()` call as we already have `sessionRequiresRestart` variable set to `true` when it already active, so it reduce call.

**Comment by weierophinney** [comment]
@samsonasik One other thing that could make this better, particularly for the use case you presented in the original issue: check to see that the storage option provided _differs_ from the one already set. If it isn't different, the method can bail early, without attempting the `ini_set()` operation at all. All that takes is an `ini_get()` call and a comparison.

**Comment by samsonasik** [comment]
@weierophinney do you mean that we need to add : `ini_get()` check before `ini_set()` at `SessionConfig:: setStorageOption()` ?

**Comment by weierophinney** [comment]
> do you mean that we need to add : ini_get() check before ini_set() at SessionConfig:: setStorageOption() ?

Yes; it would bail early, before any attempts to determine if the session needs to be restarted, or setting the INI value, if the values are the same.

**Comment by samsonasik** [comment]
@weierophinney I've updated to have `ini_get()` check value first before `ini_set()`

**Review by weierophinney — APPROVED** [review]

**Comment by weierophinney** [comment]
Thanks, @samsonasik!

**Comment by razonklnbd** [comment]
as suggested https://github.com/zendframework/zend-session/issues/104#issuecomment-361046136
i made change for zf2 (attached file). can someone add into repository please.

sorry, .php not supported to upload. so i'm creating txt file of Zend\Session\Config\SessionConfig.php
[session-config.txt](https://github.com/zendframework/zend-session/files/2340906/session-config.txt)
