### PR TITLE
Fix php 7 issues

### LINKED ISSUE #35: PHP 7 and redis session caching: session_regenerate_id(): Failed to create(read) session ID
We have been caching sessions with Redis in our Zend Framework 2 project (using zend-session 2.5.2) on PHP 5.6.

After upgrading from PHP 5.6 to PHP 7.0.4, there was a problem with redis session caching, resulting in the following error when users logged in: `PHP message: PHP Catchable fatal error:  session_regenerate_id(): Failed to create(read) session ID: user`.

We currently use a custom save handler to work around this problem:

```
namespace OurFramework\Session\SaveHandler;

class Cache extends \Zend\Session\SaveHandler\Cache
{    
    public function read($id)
    {
        return (string)parent::read($id);
    }
}
```

Maybe this fix could be added to `Zend\Session\SaveHandler\Cache`.

See this [question on stackoverflow](http://stackoverflow.com/questions/36130603/redis-session-caching-with-php-7-and-zf2-session-object-destruction-failed), and the discussion [here](https://bugs.php.net/bug.php?id=71187).

### LINKED ISSUE #36: PHP 7 and redis session caching: Session object destruction failed.
We have been caching sessions with Redis in our Zend Framework 2 project (using zend-session 2.5.2) on PHP 5.6.

After upgrading from PHP 5.6 to PHP 7.0.4, we get PHP warnings like `session_regenerate_id(): Session object destruction failed.  ID: user (path: tcp://host:port?weight=1&amp;timeout=3)` and `session_destroy(): Session object destruction failed` when users are logged out.

When discussing the issue on stackoverflow [here](http://stackoverflow.com/questions/36130603/redis-session-caching-with-php-7-and-zf2-session-object-destruction-failed), it was suggested that this might be a bug in zend-session.

### PR DESCRIPTION
**Pull request by zluiten**
This PR supersedes #44. It contains fixes for 
- `read` not returning always a string, fixes #35 and #41.
- `destroy` wrongly returning false when session doesn't exist. Fixes #36 and #42.

**read**
If `read` returns anything else than a string it will fail with `PHP Catchable fatal error: session_regenerate_id(): Failed to create(read) session ID: user`. PHP 7 requires that reading always returns a string, regardless the existence of data. 

**destroy**
When `session_regenerate_id()` is called right after `session_start()` php tries to destroy a session that doesn't exist yet. Currently `DbTableGateway` bases its return value on the affected rows and therefore causing `destroy()` to wrongly return `false` when the session doesn't exist yet. PHP 7 will then fail with `session_regenerate_id(): Session object destruction failed. ID: user (path: )`.

### CODE REVIEW

File: src/SaveHandler/DbTableGateway.php [hunk 1]
```diff
@@ -149,10 +149,14 @@ public function write($id, $data)
...
     {
-        return (bool) $this->tableGateway->delete([
+        $exists = (bool) $this->read($id);
+
+        $deleted = (bool) $this->tableGateway->delete([
             $this->options->getIdColumn()   => $id,
             $this->options->getNameColumn() => $this->sessionName,
         ]);
+
+        return $exists ? $deleted : true;
```
Comment (weierophinney) [inline src/SaveHandler/DbTableGateway.php:159]: Couldn't we return early if `! $exists`?

Comment (weierophinney) [inline src/SaveHandler/DbTableGateway.php:159]: I've tested this locally, and we can indeed return early. I'm making that change as part of the merge.

**Comment by weierophinney** [comment]
Thanks, @netiul !
